services:
  - type: web
    name: discord-bot-bro-backend
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
